name: Build and Release Static Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Gerar arquivos estáticos
        run: npm run build

      - name: Compactar arquivos estáticos
        run: zip -r netobaterias-estatico.zip out

      - name: Criar versão da release
        id: version
        run: echo "TAG=v1.0.$(date +%s)" >> $GITHUB_ENV

      - name: Criar release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "Arquivos estáticos gerados automaticamente."
          draft: false
          prerelease: false
          files: netobaterias-estatico.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
